### ISSUE TITLE
Need to install jquery 

### ISSUE THREAD

**Issue by itranga** [cmelion/generator-ng2-webpack#52]
What is best way to install jquery with jquey plugins generator-ng2-webpack ?

**Comment by cmelion** [comment]
First you need to add the npm packages:
`npm install --save jquery`

Next you need to add the dependencies to your [vendors.ts](https://github.com/cmelion/ng2-webpack-demo-app/blob/master/src/vendor.ts):

```
// Polyfills
// fixes for non ES6 browsers (IE, safari, ...)
// Polyfills
import 'es6-shim';
import 'reflect-metadata';
require('zone.js/dist/zone');


// Angular 2
import '@angular/platform-browser';
import '@angular/core';
import '@angular/router-deprecated';
import '@angular/http';

// RxJS
import 'rxjs';

// Other vendors for example jQuery, Lodash or Bootstrap
import 'jquery';
// You can import js, ts, css, sass, ...
```

**Comment by itranga** [comment]
Thanks  . What is the better way to add jquery plugin ? 

Example : http://ionden.com/a/plugins/ion.rangeSlider/en.html

**Comment by mattxo** [comment]
@itranga It's the same as @cmelion showed.

`npm install ion-rangeslider`

Then in vendor.ts

```
// Polyfills
// fixes for non ES6 browsers (IE, safari, ...)
// Polyfills
import 'es6-shim';
import 'reflect-metadata';
require('zone.js/dist/zone');


// Angular 2
import '@angular/platform-browser';
import '@angular/core';
import '@angular/router-deprecated';
import '@angular/http';

// RxJS
import 'rxjs';

// Other vendors for example jQuery, Lodash or Bootstrap
import 'jquery';
import 'ion-rangeslider';
// You can import js, ts, css, sass, ...
```

**Comment by cmelion** [comment]
@itranga did adding your dependencies to vendors.js work for you?

**Comment by itranga** [comment]
I added jquery and ion-rangeslider vendor.ts. what is better way to add jquery and ion-rangeslider  inside Angular2 Component ?

**Comment by mattxo** [comment]
You may wish to install the typings files (*.d.ts) as well. For jquery, you can do this with 

`typings install jquery`

You may be able to do the same with ion-rangeslider, otherwise, you can get the .d.ts files directly from 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ion.rangeSlider/ion.rangeSlider.d.ts

And reference them to your /typings/main.d.ts file 

eg. `/// <reference path="main/definitions/ion-rangeslider/ion-rangeslider.d.ts" />`

If you've saved the typings file to `main/definitions/ion-rangeslider`

**Comment by cmelion** [comment]
using [the wiki](https://github.com/cmelion/generator-ng2-webpack/wiki/Importing-vendor-libs) to capture issues like this one.
